name: Promote Dispatch

on:
  repository_dispatch:
    types: [promote-command]
jobs:
  promote-release:
    if: ${{ github.event.client_payload.slash_command.env }} && ${{ github.event.client_payload.slash_command.name }}
    runs-on: ubuntu-latest
    steps:
    - name: Set Env Variables
      id: env_var
      run: |
        echo ::set-output name=requestor::$(jq .client_payload.actor $GITHUB_EVENT_PATH)
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.client_payload.slash_command.name }}
    - name: GitHub Pull Request Action
      uses: repo-sync/pull-request@v2.2
      with:
        source_branch: ${{ github.event.client_payload.slash_command.name }}
        destination_branch: ${{ github.event.client_payload.slash_command.env }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
        pr_title: "Promoting ${{ github.event.client_payload.slash_command.name }} to ${{ github.event.client_payload.slash_command.env }}"
        pr_body: "Promoting release ${{ github.event.client_payload.slash_command.name }} to the ${{ github.event.client_payload.slash_command.env }} environment as requested by ${{ steps.env_var.outputs.requestor }}."


