name: Release Dispatch

on:
  repository_dispatch:
    types: [release-command]
jobs:
  create-release-branch:
    if: ${{ github.event.client_payload.slash_command.name }}
    runs-on: ubuntu-latest
    steps:
    - name: Check if release branch exists
      id: release_check
      run: |
        echo ::set-output name=release::$(git ls-remote --heads https://github.com/$GITHUB_REPOSITORY ${{ github.event.client_payload.slash_command.name }})
    - name: Create release branch
      uses: peterjgrainger/action-create-branch@v1.0.0
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        branch: ${{ github.event.client_payload.slash_command.name }}
      if: ${{ steps.release_check.outputs.release == null }}
    - name: Alert that release already exists
      run: |
        echo "Release branch ${{ github.event.client_payload.slash_command.name }} already exists. Skipping..."
      if: ${{ steps.release_check.outputs.release != null }}

  update-release-pointers:
    runs-on: ubuntu-latest
    needs: create-release-branch
    steps:
    - uses: actions/checkout@v2
    - name: Update Frontend Release
      if: ${{ github.event.client_payload.slash_command.frontend != null }} 
      uses: mikefarah/yq@3.3.2 
      with:
        cmd: w $GITHUB_WORKSPACE/values.yaml applicationVersions.frontend ${{ github.event.client_payload.slash_command.frontend }}

#  release-input-notify:
#    runs-on: ubuntu-latest
#    strategy:
#      matrix:
#        repos:
#        - approval-flow-notify
#    steps:
#    - uses: actions/github-script@v1
#      with:
#        github-token: ${{secrets.ALERT_TOKEN}}
#        script: |
#          github.issues.create({
#            owner: context.repo.owner,
#            repo: "${{matrix.repos}}",
#            title: "Release Input Required: ${{ github.event.client_payload.slash_command.name }}",
#            body: "The release process for ${{ github.event.client_payload.slash_command.name }} has begun. Please visit [here](https://github.com) to provide your input."
#          }) 
