name: Release Dispatch

on:
  repository_dispatch:
    types: [release-command]
jobs:
  release-info:
    runs-on: ubuntu-latest
    steps:
    - run: |
        cat $GITHUB_EVENT_PATH

  create-release-branch:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo ${{ github.event.client_payload.slash_command.name }}
    - uses: peterjgrainger/action-create-branch@v1.0.0
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        branch: ${{ github.event.client_payload.slash_command.name }}
  release-input-notify:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repos:
        - approval-flow-notify
    steps:
    - uses: actions/github-script@v1
      with:
        github-token: ${{secrets.ALERT_TOKEN}}
        script: |
          github.issues.create({
            owner: context.repo.owner,
            repo: "${{matrix.repos}}",
            title: "Release Input Required: ${{ github.event.client_payload.slash_command.name }}",
            body: "The release process for ${{ github.event.client_payload.slash_command.name }} has begun. Please visit [here](https://github.com) to provide your input."
          }) 
